config/routes.rb
Rails.application.routes.draw do
    resources :groups
  root 'groups#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ActiveRecord::Base
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  def index
    @groups = Group.all
  end
  def new
     @group = Group.new
  end

  def show
       @group = Group.find(params[:id])
     end


   #new add crud
    def create
      @group = Group.new(group_params)

      #validate
      if @group.save
        redirect_to groups_path
      else
        render :new
      end
    end

  def edit
    @group = Group.find(params[:id])
  end

  def update
        @group = Group.find(params[:id])

        #@group.update(group_params)  redirect_to groups_path, notice: "Update Success"

        if @group.update(group_params)
          redirect_to groups_path, notice: "Update Success"
        else
          render :edit
        end
  end

    def destroy
        @group = Group.find(params[:id])
        @group.destroy
        flash[:alert] = "Group deleted"
        redirect_to groups_path
      end

    private

    def group_params
      params.require(:group).permit(:title, :description)
    end



end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    flash[:notice] = "早安！你好！"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flashes_helper.rb
module FlashesHelper
  FLASH_CLASSES = { alert: "danger", notice: "success", warning: "warning"}.freeze
  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end
  def user_facing_flashes
    flash.to_hash.slice "alert", "notice","warning"
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class="alert alert-dismissable alert-<%= flash_class(key) %>">
      <button class="close" data-dismiss="alert">×</button>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_footer.html.erb
<footer class="container" style="margin-top: 100px;">
    <p class="text-center">Copyright ©2016 Rails101
        <br>Design by
        <a href="http://courses.growthschool.com/courses/rails-101/" target=_new>xdite</a>
    </p>
</footer>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <a class="navbar-brand" href="/">Rails 101</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <%= link_to("登入", '#') %>
                </li>
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container-fluid -->
</nav>

app/views/groups/_form.html.erb
<%= simple_form_for @group do |f| %>
    <div class="form-group">
      <%= f.input :title, input_html: { class: "form-control"} %>
      <%= f.input :description, input_html: { class: "form-control"} %>
    </div>
    <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submitting..." } %>
<% end %>

<% if false %>


    <%= form_for @group do |f| %>
        <div class="form-group">
          <div class="form-group string optional">
            <%= f.label "title", :class => "string optional control-label" %>
            <%= f.text_field :title, :class => "string optional form-control form-control" %>
          </div>
          <div class="form-group string optional">
            <%= f.label "description", :class => "string optional control-label" %>
            <%= f.text_area :description, :class => "string optional form-control" %>
          </div>
        </div>
        <%= f.submit "Submit", class: "btn btn-primary", data: { disable_with: "Submitting..." } %>
    <% end %>


<% end %>

app/views/groups/edit.html.erb
<div class="col-md-4 col-md-offset-4">
  <h2>编辑讨论版</h2>
  <hr>


  <%= render "form" %>

</div>

app/views/groups/index.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to("New group", new_group_path, class: "btn btn-primary pull-right") %>
  </div>
  <table class="table table-hover">
    <thead>
      <tr>
        <td>#</td>
        <td>Title</td>
        <td>Description</td>
      </tr>
    </thead>
    <tbody>
      <% @groups.each do |group| %>
        <tr>
          <td>#</td>
          <td><%= link_to(group.title, group_path(group)) %></td>
          <td><%= group.description %></td>
          <td>
              <%= link_to("Edit", edit_group_path(group), class: "btn btn-sm btn-default")%>
              <%= link_to("Delete", group_path(group),    class: "btn btn-sm btn-default",
                          method: :delete, data: { confirm: "Are you sure?" } )%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/groups/new.html.erb
<div class="col-md-4 col-md-offset-4">
    <h2>新增讨论版</h2>



  <hr>
  <%= render "form" %>


</div>

app/views/groups/show.html.erb
<div class="col-md-12">
  <div class="group">
    <%= link_to("Edit", edit_group_path(@group), class: "btn btn-primary pull-right")%>
  </div>
  <h2><%= @group.title %></h2>
  <p><%= @group.description %></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
        <title>Rails101</title>
        <%= csrf_meta_tags %>
        <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
        <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>
    <body>
        <div class="container-fluid">
            <%= render "common/navbar" %>
            <%= render "common/flashes" %>
            <%= yield %>
        </div>
        <%= render "common/footer" %>
    </body>
</html>

app/views/welcome/index.html.erb
<h1> Hello World! 123</h1>

<h1>This is a Heading</h1>
<p>This is a paragraph.</p>
<img src="https://external.fkul8-1.fna.fbcdn.net/safe_image.php?d=AQAgzKZlEbrZzhBN&w=476&h=249&url=http%3A%2F%2Fwww.channelnewsasia.com%2Fimage%2F10067268%2F16x9%2F991%2F529%2F24bdb2a9064da1406c87b5eb77bca5a0%2FPX%2Ffile-photo--employees-work-inside-uber-coe-in-cairo-9.jpg&cfs=1&upscale=1&fallback=news_d_placeholder_publisher&_nc_hash=AQDDyF7MkOsx2hVN" alt="Girl in a jacket" width="500" height="600">